[env]
TERM = "xterm-256color"
WINIT_X11_SCALE_FACTOR = "1"

[window]
dynamic_padding = true
decorations = "full"
title = "Alacritty@CachyOS"
opacity = 0.8
decorations_theme_variant = "Dark"
padding.x = 16
padding.y = 16

[window.dimensions]
columns = 100
lines = 30

[window.class]
instance = "Alacritty"
general = "Alacritty"

[scrolling]
history = 10000
multiplier = 3

[colors]
draw_bold_text_with_bright_colors = true


# Emperor (black-metal-theme-neovim)
# Pure black terminal variant

[colors.primary]
background = "#000000"
foreground = "#c1c1c1"

[colors.cursor]
text   = "#000000"
cursor = "#c1c1c1"

[colors.selection]
text       = "#c1c1c1"
background = "#333333"

# -------------------
# ANSI Normal
# -------------------
[colors.normal]
black   = "#111111"
red     = "#5f8787"
green   = "#c1c1c1"
yellow  = "#888888"
blue    = "#aaaaaa"
magenta = "#999999"
cyan    = "#756482"
white   = "#c1c1c1"

# -------------------
# ANSI Bright
# -------------------
[colors.bright]
black   = "#505050"
red     = "#5f8787"
green   = "#c1c1c1"
yellow  = "#888888"
blue    = "#aaaaaa"
magenta = "#A8A1DE"
cyan    = "#756482"
white   = "#ffffff"


#[colors.primary]
##background = "#1d1f21"
#background = "#000000"
#foreground = "#c5c8c6"
#
#[colors.cursor]
#text   = "#1d1f21"
#cursor = "#c5c8c6"
#
#[colors.selection]
#background = "#373b41"
#text = "#c5c8c6"
#
#[colors.normal]
#black   = "#1d1f21"
#red     = "#cc6666"
#green   = "#b5bd68"
#yellow  = "#f0c674"
#blue    = "#81a2be"
#magenta = "#b294bb"
#cyan    = "#8abeb7"
#white   = "#c5c8c6"
#
#[colors.bright]
#black   = "#373b41"
#red     = "#cc6666"
#green   = "#b5bd68"
#yellow  = "#f0c674"
#blue    = "#81a2be"
#magenta = "#b294bb"
#cyan    = "#8abeb7"
#white   = "#e0e0e0"


[font]
size = 12
builtin_box_drawing = false
offset.x = 0
offset.y = 0
glyph_offset.x = 0
glyph_offset.y = 0

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[selection]
semantic_escape_chars = ",â”‚`|:\"' ()[]{}<>\t"
save_to_clipboard = true

[cursor]
style = "Underline"
vi_mode_style = "None"
unfocused_hollow = true
thickness = 0.15

[mouse]
hide_when_typing = true

[[mouse.bindings]]
mouse = "Middle"
action = "PasteSelection"

[keyboard]
[[keyboard.bindings]]
key = "Paste"
action = "Paste"

[[keyboard.bindings]]
key = "Copy"
action = "Copy"

[[keyboard.bindings]]
key = "L"
mods = "Control"
action = "ClearLogNotice"

[[keyboard.bindings]]
key = "L"
mods = "Control"
mode = "~Vi"
chars = "\f"

[[keyboard.bindings]]
key = "PageUp"
mods = "Shift"
mode = "~Alt"
action = "ScrollPageUp"

[[keyboard.bindings]]
key = "PageDown"
mods = "Shift"
mode = "~Alt"
action = "ScrollPageDown"

[[keyboard.bindings]]
key = "Home"
mods = "Shift"
mode = "~Alt"
action = "ScrollToTop"

[[keyboard.bindings]]
key = "End"
mods = "Shift"
mode = "~Alt"
action = "ScrollToBottom"

[[keyboard.bindings]]
key = "V"
mods = "Control|Shift"
action = "Paste"

[[keyboard.bindings]]
key = "C"
mods = "Control|Shift"
action = "Copy"

[[keyboard.bindings]]
key = "F"
mods = "Control|Shift"
action = "SearchForward"

[[keyboard.bindings]]
key = "B"
mods = "Control|Shift"
action = "SearchBackward"

[[keyboard.bindings]]
key = "C"
mods = "Control|Shift"
mode = "Vi"
action = "ClearSelection"

[[keyboard.bindings]]
key = "Key0"
mods = "Control"
action = "ResetFontSize"

[general]
live_config_reload = true
working_directory = "None"
